# COMPONENT: OPENTELEMETRY TRACING
# A pluggable module that adds OTEL annotations.
kind: Component
apiVersion: kustomize.config.k8s.io/v1alpha1
metadata:
  name: otel-tracing

patches:
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: unused
    spec:
      template:
        metadata:
          annotations:
            instrumentation.opentelemetry.io/inject-java: "true"
